{{- if not .Values.config.exporterConfig.existingSecret.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  {{- with (include "prometheus-postgres-exporter.secrets.exporterConfig.annotations" . | fromYaml) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with (include "prometheus-postgres-exporter.secrets.exporterConfig.labels" . | fromYaml) }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ include "prometheus-postgres-exporter.fullname" . }}-exporter-config
  namespace: {{ .Release.Namespace }}
stringData:
  exporterConfig.yaml: |
    {{- toYaml .Values.config.exporterConfig.secret.exporterConfig | nindent 4 }}
{{- end }}
