{{- if and (not (.Values.config.webConfig.existingSecret.enabled)) .Values.config.webConfig.secret.webConfig }}
---
apiVersion: v1
kind: Secret
metadata:
  {{- with (include "prometheus-postgres-exporter.secrets.webConfig.annotations" . | fromYaml) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with (include "prometheus-postgres-exporter.secrets.webConfig.labels" . | fromYaml) }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ include "prometheus-postgres-exporter.fullname" . }}-webconfig
  namespace: {{ .Release.Namespace }}
stringData:
  webConfig.yaml: |
    {{- toYaml .Values.config.webConfig.secret.webConfig | nindent 4 }}
{{- end }}
