{{- if not .Values.serviceAccount.existing.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- with (include "prometheus-postgres-exporter.serviceAccount.annotations" . | fromYaml) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with (include "prometheus-postgres-exporter.serviceAccount.labels" . | fromYaml) }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ include "prometheus-postgres-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  automountServiceAccountToken: {{ .Values.serviceAccount.new.automountServiceAccountToken }}
  {{- with .Values.serviceAccount.new.imagePullSecrets }}
  imagePullSecrets:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.serviceAccount.new.secrets }}
  secrets:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}