name: Helm

on:
  pull_request:
    types: [ "opened", "reopened", "synchronize" ]
  push:
    branches:
    - '**'
    tags-ignore:
    - '**'
  workflow_dispatch: {}

jobs:
  helm-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5.0.1
    - uses: azure/setup-helm@v4.3.0
      with:
        version: v4.0.0 # renovate: datasource=github-releases depName=helm/helm
    - name: Lint helm files
      run: |
        helm lint --values values.yaml .

  helm-unittest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5.0.1
    - uses: azure/setup-helm@v4.3.0
      with:
        version: v4.0.0 # renovate: datasource=github-releases depName=helm/helm
    - env:
        HELM_UNITTEST_VERSION: v1.0.0 #renovate: datasource=github-releases depName=helm-unittest/helm-unittest
      name: Install helm-unittest
      run: helm plugin install --verify=false --version "${HELM_UNITTEST_VERSION}" https://github.com/helm-unittest/helm-unittest
    - name: Execute helm unittests
      run: helm unittest --strict --file 'unittests/**/*.yaml' .
