name: Release

on:
  push:
    tags:
    - "**"

jobs:
  publish-chart:
    container:
      image: docker.io/volkerraschek/helm:3.18.2
    runs-on: ubuntu-latest
    steps:
      - name: Install tooling
        run: |
          apk update
          apk add git npm jq yq

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract meta information
        run: |
          echo "NEW_TAG="$(git tag --sort=-version:refname | head -n 1)" >> $GITHUB_ENV
          echo "OLD_TAG="$(git tag --sort=-version:refname | head -n 2 | tail -n 1)" >> $GITHUB_ENV
          echo "REPOSITORY_NAME=$(echo ${GITHUB_REPOSITORY} | cut -d '/' -f 2)" >> $GITHUB_ENV
          echo "REPOSITORY_OWNER=$(echo ${GITHUB_REPOSITORY} | cut -d '/' -f 1)" >> $GITHUB_ENV

      - name: Add Artifacthub.io annotations
        run: |
          .gitea/scripts/add-annotations.sh "${OLD_TAG}" "${NEW_TAG}"

      - name: Update Helm Chart version in README.md
        run: |
          sed -i -E "s/^CHART_VERSION=.*/CHART_VERSION=${NEW_TAG}/gm" README.md

      - name: Package chart
        run: |
          helm dependency build
          helm package --version "${NEW_TAG}" ./

      - name: Upload Chart to ChartMuseum
        env:
          CHARTMUSEUM_PASSWORD: ${{ secrets.CHARTMUSEUM_PASSWORD }}
          CHARTMUSEUM_REPOSITORY: ${{ vars.CHARTMUSEUM_REPOSITORY }}
          CHARTMUSEUM_USERNAME: ${{ secrets.CHARTMUSEUM_USERNAME }}
          CHARTMUSEUM_HOSTNAME: ${{ vars.CHARTMUSEUM_HOSTNAME }}
        run: |
          helm repo add --username ${CHARTMUSEUM_USERNAME} --password ${CHARTMUSEUM_PASSWORD} chartmuseum https://${CHARTMUSEUM_HOSTNAME}/${CHARTMUSEUM_REPOSITORY}
          helm cm-push ${REPOSITORY_NAME}-${NEW_TAG}.tgz chartmuseum
          helm repo remove chartmuseum

      - name: Upload Chart to Gitea
        env:
          GITEA_PACKAGE_REGISTRY_TOKEN: ${{ secrets.GIT_CRYPTIC_SYSTEMS_PACKAGE_REGISTRY_TOKEN }}
          GITEA_SERVER_URL: ${{ github.server_url }}
        run: |
          helm repo add --username ${REPOSITORY_OWNER} --password ${GITEA_PACKAGE_REGISTRY_TOKEN} gitea ${GITEA_SERVER_URL}/api/packages/${REPOSITORY_OWNER}/helm
          helm cm-push ${REPOSITORY_NAME}-${NEW_TAG}.tgz gitea
          helm repo remove gitea
