{{- if not (.Values.config.database.existingSecret.enabled) }}
---
apiVersion: v1
kind: Secret
metadata:
  {{- with (include "prometheus-postgres-exporter.secrets.database.annotations" . | fromYaml) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with (include "prometheus-postgres-exporter.secrets.database.labels" . | fromYaml) }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ include "prometheus-postgres-exporter.fullname" . }}-database-env
  namespace: {{ .Release.Namespace }}
stringData:
  DATA_SOURCE_URI: {{ required "No `databaseConnectionUrl` defined!" .Values.config.database.secret.databaseConnectionUrl }}
  DATA_SOURCE_USER: {{ required "No `databaseUsername` defined!" .Values.config.database.secret.databaseUsername }}
  DATA_SOURCE_PASS: {{ required "No `databasePassword` defined!" .Values.config.database.secret.databasePassword }}
{{- end }}
